name: DAST Security Scan

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    security-events: write
    issues: write

jobs:
    zap_scan:
        name: OWASP ZAP Baseline Scan
        runs-on: ubuntu-latest

        steps:
            - name: OWASP ZAP Baseline Scan
              uses: zaproxy/action-baseline@v0.14.0
              with:
                  target: "https://alejbarrero-tgf-ciberseguridad.page.gd/"
                  fail_action: false
